### PR TITLE
Add FBA package

### PR DESCRIPTION
**Pull request by glebm**
A slightly earlier version due to https://github.com/nobk/fba-sdl/issues/7

Not adding because of this and also because it takes forever to build due to not supporting parallel compilation.

[fba-rg350.opk.zip](https://github.com/glebm/od-buildroot/files/4441210/fba-rg350.opk.zip)

### CODE REVIEW

**Comment by nl255** [comment]
I have managed to get all the dependencies sorted and it compiles but when I run it there is an error that it can't find libpng16.so.16.  However if I try to compile it with -static it refuses to link and give this error "mipsel-gcw0-linux-uclibc/bin/ld: cannot find -lSDL_image".  I am using RG350_buildroot-opendingux-2014.08.  Would you mind taking a look?


https://github.com/nl255/fba-sdl/tree/working-branch-1

**Comment by glebm** [comment]
@nl255 The buildroot you're using likely has a newer version of libpng (1.6) than the firmware (probably 1.4).
Which firmware are you using? Try using the corresponding buildroot.

**Comment by nl255** [comment]
I am using Rogue CFW on the PG2v2 (which should be the same as on the rg350) with RG350_buildroot-opendingux-2014.08 which of the three I tried is the only one that wants to cooperate.  rg350_buildroot_gcc10-master gives me a bunch of errors regarding deflateEnd and such not being defined and the standard gcw0_buildroot doesn't like nlohmann/json.hpp ('to_string' is not a member of 'std').

Would your od-buildroot work?

**Comment by glebm** [comment]
No, both this and https://github.com/od-contrib/buildroot-rg350-old-kernel/releases use libpng16 by default.
However, they also provide the older libpng14 for backwards compatibility, so you can link against the older version explicitly. (e.g. `-lpng14` or `lpng1.4` instead of `-lpng`)

**Comment by nl255** [comment]
Well it compiles now but immediately segfaults when run.  All I did was edit the makefile to include the dependencies and use -lpng14 instead of -lpng.  I went ahead and uploaded it here : https://github.com/nl255/fba-sdl/tree/working-branch-2

**Pull request closed without merging**
